version: '2'
services:
    backend-app:
        image: backend
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-postgresql:5432/backend
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    backend-postgresql:
        extends:
            file: postgresql.yml
            service: backend-postgresql
