
//Fetch countries
export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

//Fetch places
export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';

//Fetch establishments places
export const FETCH_ESTABLISHMENTS_REQUEST = 'FETCH_ESTABLISHMENTS_REQUEST';
export const FETCH_ESTABLISHMENTS_SUCCESS = 'FETCH_ESTABLISHMENTS_SUCCESS';
export const FETCH_ESTABLISHMENTS_FAILURE = 'FETCH_ESTABLISHMENTS_FAILURE';

//Geocode address
export const GEOCODE_ADDRESS_REQUEST = 'GEOCODE_ADDRESS_REQUEST';
export const GEOCODE_ADDRESS_SUCCESS = 'GEOCODE_ADDRESS_SUCCESS';
export const GEOCODE_ADDRESS_FAILURE = 'GEOCODE_ADDRESS_FAILURE';

//Establishments state
export const ADD_ESTABLISHMENTS = 'ADD_ESTABLISHMENTS';
export const DELETE_ESTABLISHMENT = 'DELETE_ESTABLISHMENT';
export const CLEAN_ESTABLISHMENTS = 'CLEAN_ESTABLISHMENTS';


//Change Home Screen state
export const CHANGE_HOME_SCREEN_STATE = 'CHANGE_HOME_SCREEN_STATE';



