
//Fetch countries
export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

//Fetch places
export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';

//Fetch establishments places
export const FETCH_ESTABLISHMENTS_REQUEST = 'FETCH_ESTABLISHMENTS_REQUEST';
export const FETCH_ESTABLISHMENTS_SUCCESS = 'FETCH_ESTABLISHMENTS_SUCCESS';
export const FETCH_ESTABLISHMENTS_FAILURE = 'FETCH_ESTABLISHMENTS_FAILURE';

//Fetch establishment details
export const FETCH_ESTABLISHMENT_DETAILS_REQUEST = 'FETCH_ESTABLISHMENT_DETAILS_REQUEST';
export const FETCH_ESTABLISHMENT_DETAILS_SUCCESS = 'FETCH_ESTABLISHMENT_DETAILS_SUCCESS';
export const FETCH_ESTABLISHMENT_DETAILS_FAILURE = 'FETCH_ESTABLISHMENT_DETAILS_FAILURE';

//Geocode address
export const GEOCODE_ADDRESS_REQUEST = 'GEOCODE_ADDRESS_REQUEST';
export const GEOCODE_ADDRESS_SUCCESS = 'GEOCODE_ADDRESS_SUCCESS';
export const GEOCODE_ADDRESS_FAILURE = 'GEOCODE_ADDRESS_FAILURE';

//Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_RESET = 'LOGIN_RESET';

//Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_RESET = 'REGISTER_RESET';

//Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//Establishments state
export const ADD_ESTABLISHMENTS = 'ADD_ESTABLISHMENTS';
export const DELETE_ESTABLISHMENT = 'DELETE_ESTABLISHMENT';
export const CLEAN_ESTABLISHMENTS = 'CLEAN_ESTABLISHMENTS';


//Change Home Screen state
export const CHANGE_HOME_SCREEN_STATE = 'CHANGE_HOME_SCREEN_STATE';

//Change Establishment Screen state
export const CHANGE_ESTABLISHMENT_SCREEN_STATE = 'CHANGE_ESTABLISHMENT_SCREEN_STATE';


//Change EstablishmentDetails Screen state
export const CHANGE_ESTABLISHMENT_DETAILS_SCREEN_STATE = 'CHANGE_ESTABLISHMENT_DETAILS_SCREEN_STATE';

//Change Home Screen state
export const CHANGE_CREATE_SCREEN_STATE = 'CHANGE_CREATE_SCREEN_STATE';



